OnlineShopTime/OnlineShopTime/Models/Offers.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopTime.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Offers
    {
        public Offers()
        {
            this.Comments = new HashSet<Comments>();
            this.OfferRaiting = new HashSet<OfferRaiting>();
            this.Orders = new HashSet<Orders>();
            this.Tags = new HashSet<Tags>();
        }
    
        public string OfferID { get; set; }
        [Required(ErrorMessage = "BLA BLA BLA")]
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
        public string OfferedBy { get; set; }
        public string Photo1URL { get; set; }
        public string Photo2URL { get; set; }
        public string Photo3URL { get; set; }
        public string Photo4URL { get; set; }
        public string Price { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<OfferRaiting> OfferRaiting { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Tags> Tags { get; set; }
    }
}

OnlineShopTime/OnlineShopTime/Controllers/OfferController.cs
using Microsoft.AspNet.Identity;
using OnlineShopTime.Models;
using OnlineShopTime.Utils;
using SimpleLucene.Impl;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShopTime.Controllers
{
    public class OfferController : Controller
    {
        WorkWithOffers WWO;

        [HttpGet]
        public ActionResult Create(string OfferID)
        {
            Offers Offer;
            if (OfferID == null)
            {
                Offer = new Offers();
            }
            else
            {
                WorkWithOffers WWO = new WorkWithOffers(Server);
                Offer = WWO.GetOfferByID(OfferID);
                ViewBag.Currency = WWO.GetAndDeleteCurrency(Offer);

                imageURLs.Clear();
                if (Offer.Photo1URL != null) imageURLs.Enqueue(Offer.Photo1URL);
                if (Offer.Photo2URL != null) imageURLs.Enqueue(Offer.Photo2URL);
                if (Offer.Photo3URL != null) imageURLs.Enqueue(Offer.Photo3URL);
                if (Offer.Photo4URL != null) imageURLs.Enqueue(Offer.Photo4URL);
            }

            WorkWithTags WWT = new WorkWithTags();

            ViewBag.Tags = WWT.GetTagsNamesList();

            if (ViewBag.Currency == null)
                ViewBag.Currency = "USA";

            if (User.Identity.Name == "")
            {
                return RedirectToAction("AccessDenied", "AccessDenied");
            }
            else
                return View(Offer);
        }

        [HttpPost]
        public ActionResult Create(Offers newOffer, string Currency, string TagsString)
        {
            if (User.Identity.Name != "")
            {

                WWO = new WorkWithOffers(Server);
                string defaultImage = null;
                newOffer.Photo1URL = imageURLs.Count > 0 ? imageURLs.Dequeue() : defaultImage;
                newOffer.Photo2URL = imageURLs.Count > 0 ? imageURLs.Dequeue() : defaultImage;
                newOffer.Photo3URL = imageURLs.Count > 0 ? imageURLs.Dequeue() : defaultImage;
                newOffer.Photo4URL = imageURLs.Count > 0 ? imageURLs.Dequeue() : defaultImage;
                newOffer.Price = newOffer.Price + ' ' + Currency;              
                imageURLs.Clear();
                if((newOffer.Name == "") || (newOffer.Name == null))
                {
                    if (newOffer.OfferID != null)
                    {
                        WWO.DeleteOfferTags(newOffer.OfferID);
                        WWO.AddTagsToOffer(newOffer.OfferID, TagsString);
                    }
                    WorkWithTags WWT = new WorkWithTags();
                    ViewBag.Tags = WWT.GetTagsNamesList();
                    return View(newOffer);
                }
                string OfferID = WWO.AndNewOrModify(newOffer, User.Identity.Name);
                WWO.DeleteOfferTags(OfferID);
                WWO.AddTagsToOffer(OfferID, TagsString);
                WWO.CreateIndex(newOffer);
                imageURLs.Clear();
                return RedirectToAction("TabClick", "Home", new { TabID = 3 });
            }
            else
            {
                return RedirectToAction("AccessDenied", "AccessDenied");
            }
        }

        static Queue<string> imageURLs = new Queue<string>();

        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        public void AddImageToOffer()
        {
            if (imageURLs.Count >= 4)
                return;

            var headers = HttpContext.Request.Headers;

            string content = null;
            using (StreamReader reader = new StreamReader(HttpContext.Request.InputStream))
            {
                content = reader.ReadToEnd();
            }

            if (String.IsNullOrEmpty(content)) return;

            Dictionary<string, string> results = new Dictionary<string, string>();

            string[] pairs = content.Split(new char[] { '&' }, StringSplitOptions.RemoveEmptyEntries);
            foreach (var pair in pairs)
            {
                string[] splittedPair = pair.Split('=');

                results.Add(splittedPair[0], splittedPair[1]);
            }

            imageURLs.Enqueue(results["public_id"]);
        }

        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        public void DeleteImageFromOffer()
        {
            string content;
            using (StreamReader reader = new StreamReader(HttpContext.Request.InputStream))
            {
                content = reader.ReadToEnd();
            }
            var tmp = imageURLs.ToList();
            tmp.Remove(content);
            imageURLs = new Queue<string>(tmp);
        }

        [HttpGet]
        public ActionResult ShowUserOffers(String UserID)
        {
            if (User.Identity.Name != "")
            {
                if (UserID == null)
                    UserID = (string)Session["UserID"];

                WorkWithOffers WWO = new WorkWithOffers(Server);
                WorkWithUsers WWU = new WorkWithUsers();

                IQueryable<Offers> UserOffers = WWO.GetUserOffers(UserID);

                Users ActiveUser = WWU.GetUserByID(UserID);
                ViewBag.UserName = ActiveUser.FirstName + " " + ActiveUser.LastName;

                Session["UserID"] = UserID;
                return View(UserOffers);
            }
            else
                return RedirectToAction("AccessDenied", "AccessDenied");
        }
        public ActionResult OfferPage(String OfferID)
        {
            WorkWithOffers WWO = new WorkWithOffers(Server);
            Offers ShowOffer = new Offers();
            if (OfferID == null)
            {
                ShowOffer = (Offers)Session["ShowOffer"];
            }
            else
                ShowOffer = WWO.GetOfferByID(OfferID);
            Session["ShowOffer"] = ShowOffer;

            if (User.Identity.Name != "")
            {
                WorkWithUsers WWU = new WorkWithUsers();
                if (WWU.GetUserRole(IdentityExtensions.GetUserId(User.Identity)) == "Banned")
                    return RedirectToAction("UserBanned", "AccessDenied");
            }
            return View(ShowOffer);
        }

        public ActionResult Delete(string OfferID)
        {
            WorkWithOffers WWO = new WorkWithOffers(Server);
            WWO.DeleteOffer(OfferID);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult DeleteOffer(string OfferID)
        {
            if (OfferID == null)
                OfferID = (string)Session["OfferID"];
            Session["OfferID"] = OfferID;
            WorkWithOffers WWO = new WorkWithOffers(Server);
            return View(WWO.GetOfferByID(OfferID));
        }

        public ActionResult Search(string searchText, bool? orderByDate)
        {
            string IndexPath = Server.MapPath("~/Index");
            var indexSearcher = new DirectoryIndexSearcher(new DirectoryInfo(IndexPath), true);
            using (var searchService = new SearchService(indexSearcher))
            {
                var query = new OfferQuery().WithKeywords(searchText);
                var result = searchService.SearchIndex<Offers>(query.Query, new OfferResultDefinition());

                if (orderByDate.HasValue)
                {
                    return View(result.Results.OrderBy(x => x.DateAndTime).ToList());
                }
                return View("Search", result.Results.ToList());
            }
        }

        public void AddComment()
        {
            string message = Request.Form["Message"];
            string offerID = Request.Form["OfferID"];
            string userID = Request.Form["PostedBy"];

            Comments comment;
            using (ShopDBEntities db = new ShopDBEntities())
            {
                comment = new Comments()
                {
                    Message = message,
                    OfferID = offerID,
                    PostedBy = userID,
                    DateAndTime = DateTime.Now,
                    Users = db.Users.FirstOrDefault(m => m.UserID == userID),
                    Offers = db.Offers.FirstOrDefault(m => m.OfferID == offerID),
                    CommentID = Guid.NewGuid().ToString()
                };

                db.Comments.Add(comment);
                db.SaveChanges();
            }
            Response.Write(comment.CommentID);
        }

        public ActionResult GetComment(string commentId)
        {
            Comments comment;
            ShopDBEntities db = new ShopDBEntities();
            
                comment = db.Comments.FirstOrDefault(m => m.CommentID == commentId);
            
            return PartialView("CommentPartial", comment);
        }
    }
}

OnlineShopTime/OnlineShopTime/Views/Offer/CommentPartial.cshtml
@model OnlineShopTime.Models.Comments
@using Microsoft.AspNet.Identity

<div class="media" id="comment">
    <div class="pull-left">
        <img class="media-object" src="http://res.cloudinary.com/itransition/image/upload/c_fill,h_130,w_130/@Model.Users.AvatarURL" alt="...">
    </div>
    <div class="media-body">
        <div class="media-heading">
            <h4 style="display:inline">
                @{
                    float? likesCount = Model.Users.UserRaiting.Where(m => m.UserID == Model.Users.UserID && m.Rating == 1).Sum(m => m.Rating);
                    float? dislikesCount = Model.Users.UserRaiting.Where(m => m.UserID == Model.Users.UserID && m.Rating == -1).Sum(m => m.Rating) * -1;
                }
                @if ((Model.Users.FirstName != null) || (Model.Users.LastName != null))
                {
                    String DisplayName = Model.Users.FirstName + " " + Model.Users.LastName;
                    @Html.ActionLink((string)DisplayName, "ShowUserOffers", "Offer", new { UserID = @Model.PostedBy }, new { @style = "margin-top:0px", @class = "well well-sm" })
                }
                else
                {
                    @Html.ActionLink(Model.Users.UserName, "ShowUserOffers", "Offer", new { UserID = @Model.PostedBy }, new { @style = "margin-top:0px", @class = "well well-sm" })
                }
            </h4>
            <div id="like-buttons" style="display:inline">
                <button class="btn btn-sm btn-primary" data-userid="@Model.Users.UserID" data-voterid="@User.Identity.GetUserId()" id="like"><span id="likenum">@likesCount</span>  <span class="glyphicon glyphicon-thumbs-up"></span></button>
                <button class="btn btn-sm btn-danger" data-userid=@Model.Users.UserID data-voterid="@User.Identity.GetUserId()" id="dislike"><span class="glyphicon glyphicon-thumbs-down"></span> <span id="dislikenum">@dislikesCount</span></button>
            </div>
            <div style="display:inline; float:right">
                @Model.DateAndTime
            </div>
            </div>
        @Model.Message
    </div>
</div>

OnlineShopTime/OnlineShopTime/Views/Offer/Create.cshtml
@model OnlineShopTime.Models.Offers
@using CloudinaryDotNet
@using OnlineShopTime.Utils
@using OnlineShopTime.Models

@{
    if (Model.OfferID == null)
    {
        ViewBag.Title = Resources.Home.CreateOffer;
    }
    else
    {
        ViewBag.Title = Resources.Home.Edit;
    }
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">

        @if (Model.OfferID == null)
        {
            <h2>@Resources.Home.CreateOffer</h2>
        }
        else
        {
            <h2>@Resources.Home.Edit</h2>
        }

        @Html.ValidationSummary(true)
        <div class="jumbotron">
            <div class="row clearfix">
                <div class="col-md-8 column">
                    <form class="form-horizontal" role="form">

                        <div class="form-group">
                            <label for="inputTitle" class="control-label">@Resources.Home.OfferPageTitleLabel:</label>
                            <input type="text" name="Name" maxlength="75" style="width: 100%; max-width: 100%; max-height: 35px" class="form-control" id="inputTitle" placeholder="@Resources.Home.OfferPageTitleLabel" value="@Model.Name" />
                            <span class="field-validation-error" data-valmsg-for="Name" data-valmsg-replace="true">@Resources.Home.EmptyNameError</span>
                        </div>

                        <div class="form-group">
                            <label for="inputDescription" class="control-label">@Resources.Home.OfferPageDescriptionLabel:</label>
                            <textarea class="form-control" name="Description" style="width: 100%; max-width: 100%; min-width: 100%;" id="inputDescription" placeholder="@Resources.Home.OfferPageDescriptionLabel">@Model.Description</textarea>
                        </div>

                        <div class="form-group">
                            <label class="control-label">@Resources.Home.OfferPageTagsLabel:</label>

                            @{string TagsString = "";}
                            @if (Model.Tags.Count != 0)
                            {
                                foreach (Tags Tag in Model.Tags)
                                {
                                    TagsString = TagsString + ',' + Tag.Name;
                                }
                            }
                            <input name="TagsString" id="mySingleField" hidden="hidden" value="@TagsString">
                            <div class="">
                                <ul style="background-color: #fff; max-height: 37px" class="form-control" id="singleFieldTags"></ul>
                            </div>
                        </div>

                        <div class="row" style="margin-top: 3%">



                            <div class="col-lg-1 col-md-1" style="margin-top: 1%">
                                <label class="control-label">@Resources.Home.Price:</label>
                            </div>

                            <div class="col-lg-4 col-md-4">
                                <input type="text" name="Price" pattern="^[ 0-9]+$" oninvalid="setCustomValidity('@Resources.Home.PriceValidationError')" onchange="try{setCustomValidity('')}catch(e){}" class="form-control" style="margin-left: 8%;width: 90%; max-width: 100%; max-height: 36px" id="inputTags" placeholder="@Resources.Home.Price" value="@Model.Price" />
                            </div>

                            <div class="col-lg-2 col-md-2" style="margin-top: 1%; text-align: left">
                                <label class="control-label">@Resources.Home.Сurrency:</label>
                            </div>

                            <div class="col-lg-2 col-md-2">
                                <select class="form-control" name="Currency" style="max-height: 35px; padding: 0px; padding-left: 5px; padding-top: 5px; width: 100%; max-width: 100%">
                                    @if (ViewBag.Currency == "USD")
                                    {
                                        <option selected value="USD" style="margin-top: 0px">USD</option>
                                    }
                                    else
                                    {
                                        <option value="USD" style="margin-top: 0px">USD</option>
                                    }
                                    @if (ViewBag.Currency == "EUR")
                                    {
                                        <option selected value="EUR">EUR</option>
                                    }
                                    else
                                    {
                                        <option value="EUR">EUR</option>
                                    }
                                    @if (ViewBag.Currency == "RUB")
                                    {
                                        <option selected value="RUB">RUB</option>
                                    }
                                    else
                                    {
                                        <option value="RUB">RUB</option>
                                    }
                                    @if (ViewBag.Currency == "CNY")
                                    {
                                        <option selected value="CNY">CNY</option>
                                    }
                                    else
                                    {
                                        <option value="CNY">CNY</option>
                                    }
                                </select>
                            </div>

                            <div class="col-lg-3 col-md-3">
                                @if (Model.OfferID == null)
                                {
                                    <button type="submit" class="btn btn-default" style="width: 100%; margin-top: 1%; margin-bottom: 1.5%">@Resources.Home.CreateButton</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-default" style="width: 100%; margin-top: 1%; margin-bottom: 1.5%">@Resources.Home.Edit</button>
                                }
                            </div>

                        </div>

                    </form>
                </div>
                <div class="col-md-4 column">
                    <form>
                        @Cloud.Api.BuildUploadForm("test-field", "auto", new SortedDictionary<string, object>() { { "tags", (object)"direct_photo_album" } }, new Dictionary<string, string>() { { "multiple", "false" } })
                    </form>
                    <div class="progress progress-striped" style="width:70%" id="progress" hidden="hidden">
                        <div class="progress-bar" role="progressbar" style="width: 100%">
                        </div>
                    </div>
                    <br />
                    <div class="uploaded_info_holder" style="max-width: 310px; max-height: 310px; min-width: 310px; min-height: 310px; ">
                        @if (Model.Photo1URL != null)
                        {
                            <div class="uploaded_info" id="@Model.Photo1URL" style="float: left">
                                @Cloud.Api.UrlImgUp.Transform(new Transformation().Width(150).Height(150).Crop("fill")).BuildImageTag(Model.Photo1URL)
                                <a href="#" class="delete_img" id="@Model.Photo1URL"><span class="glyphicon glyphicon-remove-circle" style="font-size:20px"></span></a>
                            </div>
                        }
                        @if (Model.Photo2URL != null)
                        {
                            <div class="uploaded_info" id="@Model.Photo2URL" style="float: right">
                                @Cloud.Api.UrlImgUp.Transform(new Transformation().Width(150).Height(150).Crop("fill")).BuildImageTag(Model.Photo2URL)
                                <a href="#" class="delete_img" id="@Model.Photo2URL"><span class="glyphicon glyphicon-remove-circle" style="font-size:20px"></span></a>
                            </div>
                        }
                        @if (Model.Photo3URL != null)
                        {
                            <div class="uploaded_info" id="@Model.Photo3URL" style="float: left">
                                @Cloud.Api.UrlImgUp.Transform(new Transformation().Width(150).Height(150).Crop("fill")).BuildImageTag(Model.Photo3URL)
                                <a href="#" class="delete_img" id="@Model.Photo3URL"><span class="glyphicon glyphicon-remove-circle" style="font-size:20px"></span></a>
                            </div>
                        }
                        @if (Model.Photo4URL != null)
                        {
                            <div class="uploaded_info" id="@Model.Photo4URL" style="float: right">
                                @Cloud.Api.UrlImgUp.Transform(new Transformation().Width(150).Height(150).Crop("fill")).BuildImageTag(Model.Photo4URL)
                                <a href="#" class="delete_img" id="@Model.Photo4URL"><span class="glyphicon glyphicon-remove-circle" style="font-size:20px"></span></a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<style>
    div.uploaded_info {
        margin-bottom: 10px;
        position: relative;
    }

        div.uploaded_info:hover a {
            display: block;
        }

        div.uploaded_info a {
            position: absolute;
            top: 0%;
            left: 85%;
            display: none;
        }
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

    @Cloud.GetCloudinaryJsConfig()

    <script type="text/javascript">
        $(function () {
            var count = $('.uploaded_info').length;
            if (count >= 4) {
                $('.cloudinary-fileupload').hide();
            }
            $('.cloudinary-fileupload')
            .fileupload({
                dropZone: '#direct_upload',
                start: function () {
                    $('.cloudinary-fileupload').hide();
                    $('#progress').show();
                    $('#progress').addClass('active');
                },
                progress: function () {
                    //do nothing
                },
            })
            .on('cloudinarydone', function (e, data) {
                $('.cloudinary-fileupload').show();
                $('#progress').hide();
                $('#progress').removeClass('active');
                $.post('/Offer/AddImageToOffer', data.result);
                var style = "style=\"float: right\"";
                if (count % 2 == 0)
                    style = "style=\"float: left\"";
                var id = data.result.public_id;
                var info = $('<div class="uploaded_info" ' + style + 'id="' + id + '"/>');
                $(info).append($('<div class="image"/>').append(
                  $.cloudinary.image(data.result.public_id, {
                      format: data.result.format, width: 150, height: 150, crop: "fill"
                  })
                ));
                $(info).append($('<a href="#" class="delete_img" id="' + id + '"><span class="glyphicon glyphicon-remove-circle" style="font-size:20px"></span></a>'));
                $('.uploaded_info_holder').append(info);

                $('.delete_img').unbind().click(function (event) {
                    event.preventDefault();
                    var id = $(this).attr("id");
                    $.post('/Offer/DeleteImageFromOffer', id);
                    count--;
                    $('.uploaded_info').remove('#' + id);
                    if (count < 4) {
                        $('.cloudinary-fileupload').show();
                    }
                });

                count++;
                if (count >= 4) {
                    $('.cloudinary-fileupload').hide();
                } else {
                    $('.cloudinary-fileupload').show();
                }
            });
            $('.delete_img').unbind().click(function (event) {
                event.preventDefault();
                var id = $(this).attr("id");
                $.post('/Offer/DeleteImageFromOffer', id);
                count--;
                $('.uploaded_info').remove('#' + id);
                if (count < 4) {
                    $('.cloudinary-fileupload').show();
                }
            });

            var sampleTags = new Array();

            @foreach (string Tag in ViewBag.Tags)
            {
                <text>
                    sampleTags.push('@Tag');
                </text>
            }

            $('#singleFieldTags').tagit({
                availableTags: sampleTags,
                // This will make Tag-it submit a single form value, as a comma-delimited field.
                singleField: true,
                singleFieldNode: $('#mySingleField')
            });

        });
    </script>
}

OnlineShopTime/OnlineShopTime/Views/Offer/DeleteOffer.cshtml
@model OnlineShopTime.Models.Offers

@{
    ViewBag.Title = "DeleteOffer";
}

<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
        <center><h2 class="col-lg-8">@Resources.Home.AreYouSureOfferDelete</h2></center>
        <div class="col-lg-2"></div>
    </div>
    <br />
    <div class="row">
        <div class="col-lg-3"></div>
        @Html.Partial("_OfferPartial", Model)
        <div class="col-lg-3"></div>
    </div>

    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <a href="/Offer/Delete?OfferID=@Model.OfferID" class="btn btn-default btn-danger btn-lg" style="width: 100%; margin-top: 2%">@Resources.Home.Delete</a>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

OnlineShopTime/OnlineShopTime/Views/Offer/ShowUserOffers.cshtml
@model IQueryable<OnlineShopTime.Models.Offers>
@using OnlineShopTime.Models;

@{
    ViewBag.Title = @Resources.Home.UserOffers;
}

<div class="container">
    <h2>@ViewBag.UserName</h2>
    <hr />
    <div id="offers" class="row">
        @foreach (Offers UserOffer in Model)
        {
            @Html.Partial("_OfferPartial", UserOffer);
        }
    </div>
    @if (Model.Count() == 0)
    {
        @Html.Partial("_NoUserOffers");
    }
</div>

OnlineShopTime/OnlineShopTime/Views/Offer/_GalleryItem.cshtml
@using OnlineShopTime.Utils
@using CloudinaryDotNet

@{string defaultImage = "v6ac3uaxfe5gtlqtrbr7";}

<div class="col-lg-3 col-md-3 col-xs-6 thumb">
    @{string imageURL = ViewBag.URL ?? defaultImage;}
    <a class="thumbnail" href="http://res.cloudinary.com/itransition/image/upload/@imageURL" data-gallery>
        @Cloud.Api.UrlImgUp.Transform(new Transformation().Width(400).Height(300).Crop("fill")).BuildImageTag(imageURL, "id = image", "class=img-responsive")
    </a>
</div>