OnlineShopTime/OnlineShopTime/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShopTime.Models;
using Microsoft.AspNet.Identity;

namespace OnlineShopTime.Controllers
{
    public class AdministratorController : Controller
    {
        //
        // GET: /Administrator/
        public ActionResult AdminPanel()
        {
            WorkWithUsers WWU = new WorkWithUsers();
            IQueryable<Users> Users = (IQueryable<Users>)Session["Users"];
            if (Users == null)
            {
                Users = WWU.GetWorseUsers();
                WWU.CheckUserRoles();
            }
            Session["Users"] = Users;
            if (User.Identity.Name != "")
                if (WWU.GetUserRole(IdentityExtensions.GetUserId(User.Identity)) == "Admin")
                    return View(Users);
            return RedirectToAction("AccessDenied", "AccessDenied");

        }
        public ActionResult SetRights(string UserID, string Rights)
        {
            WorkWithUsers WWU = new WorkWithUsers();
            WWU.SetUserRights(UserID, Rights);
            Session["Users"] = null;
            return RedirectToAction("AdminPanel");
        }
        public ActionResult Search(string SearchText)
        {
            WorkWithUsers WWU = new WorkWithUsers();
            if (SearchText != "")
            {
                IQueryable<Users> FiltredUsers = WWU.SearchInUsers(SearchText);
                Session["Users"] = FiltredUsers;
            }
            else
                Session["Users"] = WWU.GetWorseUsers();
            return RedirectToAction("AdminPanel");
        }
        public ActionResult ShowAdminContacts(string UserID)
        {
            WorkWithUsers WWU = new WorkWithUsers();
            return View(WWU.GetAdminsList());
        }
    }
}

OnlineShopTime/OnlineShopTime/Views/Administrator/AdminPanel.cshtml
@model IQueryable<OnlineShopTime.Models.Users>
@using OnlineShopTime.Models

@{
    ViewBag.Title = @Resources.Home.UsersRights;
}

<br />

<div class="jumbotron" style="min-width: 612px">
    @using (Html.BeginForm("Search", "Administrator", FormMethod.Post))
    {
        <div class="container">
            <div class="rows">
                <div class="col-lg-1 col-md-1 col-sm-2">
                    <center><h4 style="margin-top: 13%; margin-left: -5px">@Resources.Home.Search:</h4></center>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-7">
                    <input type="text" name="SearchText" maxlength="75" style="width: 100%; max-width: 100%; max-height: 35px" class="form-control" id="inputTitle" placeholder="@Resources.Home.EnterAnyText" />
                </div>
                <div class="col-lg-2 col-md-2 col-sm-3">
                    <button type="submit" class="btn btn-default btn-primary" style="width: 100%"><span class="glyphicon glyphicon-search"></span>&nbsp;@Resources.Home.Search</button>
                </div>
            </div>
        </div>
    }
    <br />

    <div class="container">
        <center>
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">@Resources.Home.UserList</div>
                    <table class="table table-striped">

                        <thead>
                            <tr style="height: 45px">
                                <th style="vertical-align: middle; text-align: center">#</th>
                                <th style="vertical-align: middle; text-align: center">@Resources.Home.FirstName</th>
                                <th style="vertical-align: middle; text-align: center">@Resources.Home.LastName</th>
                                <th style="vertical-align: middle; text-align: center">@Resources.Home.UserLogin</th>
                                <th style="vertical-align: middle; text-align: center">@Resources.Home.Role</th>
                                <th style="vertical-align: middle; text-align: center">@Resources.Home.Controls</th>
                            </tr>
                        </thead>

                        <tbody>
                            @{
                                int Count = 1;
                                foreach (Users User in Model)
                                {
                                    <tr style="height: 45px">
                                        <th style="vertical-align: middle; text-align: center">@Count</th>
                                        <th style="vertical-align: middle; text-align: center">
                                            @Html.ActionLink(User.FirstName, "ShowUserInfo", "Order", new { UserID = User.UserID }, htmlAttributes: new { style = "text-decoration: none", title = @Resources.Home.ShowUserContacts })
                                        </th>
                                        <th style="vertical-align: middle; text-align: center">
                                            @Html.ActionLink(User.LastName, "ShowUserOffers", "Offer", new { UserID = User.UserID }, htmlAttributes: new { style = "text-decoration: none", title = @Resources.Home.ShowUserOffers })
                                        </th>
                                        <th style="vertical-align: middle; text-align: center">@User.UserName</th>
                                        <th style="vertical-align: middle; text-align: center">@User.UserRights</th>
                                        <th style="text-align: center">


                                            <div class="dropdown">
                                                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                                                    @Resources.Home.Controls
                                                    <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu dropdown-menu-right" style="margin: 0 auto; left: 0px; width: 50px">
                                                    @if (User.UserRights == "User")
                                                    {
                                                        <li>@Html.ActionLink(Resources.Home.Ban, "SetRights", "Administrator", new { UserID = User.UserID, Rights = "Banned" }, htmlAttributes: new { style = "text-decoration: none; color: #000" })</li>
                                                        <li style="color: #d5d5d5">@Resources.Home.Unban</li>
                                                        <li style="color: #d5d5d5">@Resources.Home.Demote</li>
                                                        <li>@Html.ActionLink(Resources.Home.Promote, "SetRights", "Administrator", new { UserID = User.UserID, Rights = "Admin" }, htmlAttributes: new { style = "text-decoration: none; color: #000" })</li>
                                                    }
                                                    @if (User.UserRights == "Admin")
                                                    {
                                                        <li>@Html.ActionLink(Resources.Home.Ban, "SetRights", "Administrator", new { UserID = User.UserID, Rights = "Banned" }, htmlAttributes: new { style = "text-decoration: none; color: #000" })</li>
                                                        <li style="color: #d5d5d5">@Resources.Home.Unban</li>
                                                        <li>@Html.ActionLink(Resources.Home.Demote, "SetRights", "Administrator", new { UserID = User.UserID, Rights = "User" }, htmlAttributes: new { style = "text-decoration: none; color: #000" })</li>
                                                        <li style="color: #d5d5d5">@Resources.Home.Promote</li>
                                                    }
                                                    @if (User.UserRights == "Banned")
                                                    {
                                                        <li style="color: #d5d5d5">@Resources.Home.Ban</li>
                                                        <li>@Html.ActionLink(Resources.Home.Unban, "SetRights", "Administrator", new { UserID = User.UserID, Rights = "User" }, htmlAttributes: new { style = "text-decoration: none; color: #000" })</li>
                                                        <li style="color: #d5d5d5">@Resources.Home.Demote</li>
                                                        <li>@Html.ActionLink(Resources.Home.Promote, "SetRights", "Administrator", new { UserID = User.UserID, Rights = "Admin" }, htmlAttributes: new { style = "text-decoration: none; color: #000" })</li>
                                                    }
                                                </ul>
                                            </div>



                                        </th>
                                    </tr>
                                                    Count++;
                                }
                            }
                        </tbody>
                    </table>
                </div>
                @if (Model.Count() == 0)
                {
                    <h2> @Resources.Home.NoSearchResults </h2>
                }
            </div>
        </center>

    </div>
</div>

OnlineShopTime/OnlineShopTime/Views/Administrator/ShowAdminContacts.cshtml
@model OnlineShopTime.Models.Users
@using OnlineShopTime.Models

@{
    ViewBag.Title = "ShowAdminContacts";
}

<br>

@{ViewBag.ShowContactInfo = true;}

<center>
    @Html.Partial("_UserPartial", Model)
</center>